spring.datasource.url=jdbc:postgresql://localhost:5432/laboratorio_db
spring.datasource.username=usuario
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
jwt.secret-key=OWQzZTkyM2UzODcxMmE0Yjg3MGM1ZTlmOGY0YTEzZjYzMTRjNDA1OTA4MzJkMmUxYjFkMzgyNWI0ZDZjMGIwOA==
jwt.expiration=1800000
# Configuración de Seguridad - RF-13
# Máximo de intentos fallidos antes de bloquear
security.max-failed-attempts=5
# Duración del bloqueo en minutos
security.block-duration-minutes=15
# Horas para considerar cambio de IP sospechoso
security.suspicious-ip-change-hours=1
# Máximo de sesiones concurrentes por usuario
security.max-concurrent-sessions=3